### ISSUE TITLE
Where is the "style emulation module"?

### ISSUE THREAD

**Issue by pilwon** [web-animations/web-animations-js#30]
README says:
> to keep the size of web-animations-next-lite as small as possible, the style emulation module is not included.

Where can I find this style emulation module?

**Comment by dstockwell** [comment]
It's part of the `web-animations` and `web-animations-next` targets, but not `web-animations-next-lite`.

`web-animations-next-lite` uses `src/apply.js` while the others use `src/apply-preserving-inline-style.js`

**Comment by pilwon** [comment]
@dstockwell Thank you-

I have a question that may be somewhat related to the emulation module. Let's say we have the following animation played:

```js
let element = document.body;
let animation = document.timeline.play(
  new KeyframeEffect(element, [
    {backgroundColor: getComputedStyle(element).backgroundColor},
    {backgroundColor: 'blue'}
  ], {
    duration: 5000,
    fill: 'forwards'
  })
);
```

Why does the following successfully changes the background to red ...

```js
setTimeout(() => {
  animation.cancel();
  element.style.backgroundColor = 'red';
}, 3000);  // interrupting during the animation
```

... but the following is stuck at `offset=1`? (background stays at blue)

```js
animation.onfinish = () => {
  element.style.backgroundColor = 'red';
};
```

**Comment by dstockwell** [comment]
That's how `fill: 'forwards'` works -- the animation will continue to apply the values at the time that it finished. It's the same behavior as CSS Animations: values applied by animations will override author styles (those in stylesheets or inline styles on the page).

We're trying to find a better solution but it will have to be something additional, like a new fill mode or another flag so that we don't break existing content using CSS Animations.

@birtles, @shans

**Comment by pilwon** [comment]
@dstockwell Do we currently have a workaround for performing this kind of tasks?

**Comment by rjwright** [comment]
You can work around it. Two ways I have tried are:

1) Use fill forwards for your keyframe effect. Set an onfinish routine to cancel the keyframe effect and set the style of the target to match the end state of the keyframe effect. Then you can mutate the target however you like.
```
var keyframeEffect = new KeyframeEffect(
	box,
	[
	{left: '10px'},
	{left: '500px'}
	],
	{duration: 1500, fill: 'forwards'});

var animation = document.timeline.play(keyframeEffect);
animation.onfinish = function(e) {
		animation.cancel();
		box.style.left = '500px';
	};
// This works.
setTimeout(function() { box.style.left = '100px'; }, 2500);
```

2) Use fill none for your keyframe effect. Use a sequence effect to wrap your keyframe effect plus a custom effect to set the target style to match the end state of the keyframe effect. Again you can now mutate the target style however you need.
```
var keyframeEffect = new KeyframeEffect(
	box,
	[
	{left: '10px'},
	{left: '500px'}
	],
	{duration: 1500, fill: 'none'});

var animation;
var fakeFill = new KeyframeEffect(
	null,
	function(t) {
		if(t !== null)
			box.style.left = '500px';
	},
	// Generous duration to ensure it is sampled.
	100);

var effectWithFill = new SequenceEffect([keyframeEffect, fakeFill]);
animation = document.timeline.play(effectWithFill);
// This works.
setTimeout(function() { box.style.left = '100px'; }, 2500);
```

(1) Is neater for most cases.  The reason I say to use fill forwards in this approach is because of the chance of onfinish not firing in the next frame after the animation finishes, however I don't know whether this is actually an issue in practice. @dstockwell will know better.

(2) Could be useful if you need to "soft fill" a small part of a large animation tree.

**Comment by pilwon** [comment]
@rjwright Thanks for sharing your workarounds! That was a great help-
