### ISSUE TITLE
trying to preserve the final state causes a flicker in firefox

### ISSUE THREAD

**Issue by urandom** [web-animations/web-animations-js#41]
Say you are running the following animation on an element:

```javascript
element.animate([
            {opacity: 0.3, transform: "translate3d(105%, 0px, 0px)"},
            {opacity: 1, transform: "translate3d(0px, 0px, 0px)"},
        ], {duration: 400, easing: 'cubic-bezier(0.4, 0, 0.2, 1)'});
```

If you add the following onfinish to the animation (pseudo-code):

```javascript
anim.onfinish() {
    element.style.translate3d = "0px, 0px, 0px";
   element.style.opacity = "1";
}
```

the element will briefly flicker between the reverted state from the animation, and the state applied during onfinish. This only happens in firefox.

**Comment by alancutter** [comment]
> `element.style.translate3d = "0px, 0px, 0px";`

translate3d is not a property so this line won't do anything to the element's style although [translate](https://drafts.csswg.org/css-transforms-2/#propdef-translate) is in the works.

The flicker would be due to the asynchronous nature of Javascript events which have no timing guarantees and are not recommended for sequencing with animations.
You can either add `fill: 'forwards'` to the timing input to element.animate() or just set the final inline style when the animation is started. Animated styles apply on top of inline styles.

**Comment by urandom** [comment]
> translate3d is not a property so this line won't do anything to the element's style although translate is in the works.

Please notice the 'pseudo-code' label before that example :)
I assumed the flicker was due to the fact that onfinish was fired in a setTimeout, but it was weird that chrome didn't show that behavior.
The `fill: 'forwards'` seems interesting. Is that an option of the 'animate' method (like duration and ease)?

**Comment by alancutter** [comment]
> The fill: 'forwards' seems interesting. Is that an option of the 'animate' method (like duration and ease)?

Correct, there are several timing options available, they mostly line up with the timing properties of CSS Animations.
http://w3c.github.io/web-animations/#the-animationeffecttiming-interface
