### ISSUE TITLE
https://events.google.com/io2015/ stopped working

### ISSUE THREAD

**Issue by ebidel** [web-animations/web-animations-js#70]
Did something change in Canary 52?

![screen shot 2016-04-18 at 2 27 50 pm](https://cloud.githubusercontent.com/assets/238208/14620630/997e2676-0572-11e6-9f2e-95456f8f7fc4.png)

**Comment by samthor** [comment]
I believe this is fixed by [2.2.0](https://github.com/web-animations/web-animations-js/releases), paging @alancutter, but old sites might need to be updated.

It's to do with groups, which is why native Chrome doesn't work.

**Comment by ebidel** [comment]
There's no way around this? Any site that's been using the poylfill is going to go bust very soon :(

This is also breaking our prod site this year (https://events.google.com/io2016/) until we push a new version with 2.2.0.

**Comment by ebidel** [comment]
BTW, the console warning says Oct 2016, so I'd expect nothing to break until then  for existing sites using the polyfill.

**Comment by birtles** [comment]
Firefox Nightly reports the same error. We are waiting for an update for the Google I/O site as we were informed that this is the only site relying on this feature.

If that's so, we either need to update Google I/O or change the blink implementation, gecko implementation, spec, and polyfill.

I've offered several times to update the spec and Gecko but I believe it was thought that this was the only site affected.

**Comment by ebidel** [comment]
I can confirm it's fixed on our staging server for the new IO site. That will go out shortly. 

Now that's it's affecting last year's site (events.google.com/io2015/), I'm not sure what to do. We built that too and can update it, but I'm worried there may be other breakage. That code hasn't been touched in a year and a lot has changed. It's possible newer versions of npm/SDK deps won't be able to deploy it anymore. 

What is the spec change that's causing this error?

**Comment by birtles** [comment]
The spec was previously lax about error checking. When we met in February, we agreed we should throw exceptions for invalid timing input.

The polyfill appears to have been exploiting the fact that invalid input was allowed to store its own metadata in the 'easing' property and then, I guess, `eval()` it later.

(There is one case where the polyfill used to write all linear easings as the string `function(a) {return a}` which affects a lot of sites so both Blink and Gecko have a special-case path to not throw for that one string until usage drops sufficiently.)

If this causes too much of a compatibility issue, we can update the spec to store invalid `easing` values without throwing. We'd probably need to do that soon however since Firefox plans to ship `Element.animate` in the version that gets uplifted from trunk this weekend.

**Comment by ebidel** [comment]
Do you know if Blink is tracking the prevalence of throwing this error? I'd hate to say we should change the spec for a couple of sites. It could just be our own. I have no barometer on how many people are using the polyfill and/or exploiting the invalid input.

**Comment by alancutter** [comment]
This TypeError is due to a bug in the polyfill, fixed in 2.2.0. It's not attempting to eval() the timing function later it's just mishandling its own internal data.

Instances of this is being tracked by Blink: https://goto.google.com/vwori (internal)
So far only the linear timing functions are frequent enough to show up in the graphs.

The IO 2015 site is hitting this TypeError in Chrome canary because it's passing an easing to an AnimationGroup. Easings on groups aren't supported by the polyfill.
Debugging screenshot: http://i.imgur.com/GBE7ZVT.png
If the easing is removed from the group's timing input then the TypeError will no longer be thrown by Chrome until October 2016. Updating to web-animations-js 2.2.0 will avoid hitting the bug entirely and GroupEffect easings will be ignored instead of raising TypeErrors.

Because there are backwards incompatible changes in 2.2.0 I understand that upgrading may be painful. I'll start working on back porting the polyfill bug fix to earlier versions as a minor patch update to make fixing this less of a burden.

**Comment by alancutter** [comment]
New releases have been published with the easing TypeError fix:
https://github.com/web-animations/web-animations-js/tree/2.1.5
https://github.com/web-animations/web-animations-js/tree/2.0.1
https://github.com/web-animations/web-animations-js/tree/1.0.8

Please let me know if there are any problems with the new releases.

**Comment by diagramatics** [comment]
Have any of these versions been pushed to npm yet?

**Comment by alancutter** [comment]
Just pushed 2.1.5 to npm, sorry for the delay.
The previous versions 2.0 and 1.0 were never published on npm.

**Comment by ebidel** [comment]
events.google.com/io2016/ with 2.2.9 is out.

**Comment by kareljan** [comment]
This is not realy related to this. But is there a blogpost somewhere that explains how the events.google.com/io2016/ site is made? which technologies are used and how the clock is done?

**Comment by naoak** [comment]
@kareljan
The source code is open at https://github.com/GoogleChrome/ioweb2016

**Comment by ebidel** [comment]
[My session](https://events.google.com/io2016/schedule?sid=15631cfd-0bef-e511-a517-00155d5066d7#day1/15631cfd-0bef-e511-a517-00155d5066d7) at I/O talks about how we built the app. The video will be up later today.
